# Generated by Django 6.0.1 on 2026-01-31 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('university', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('batch_year', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('batch_year', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('initials_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('nic', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('permanent_address', models.TextField()),
                ('student_reg_no', models.CharField(max_length=50)),
                ('degree_nvq_level', models.CharField(max_length=100)),
                ('degree_diploma_name', models.CharField(max_length=255)),
                ('training_district', models.CharField(max_length=100)),
                ('divisional_secretariat', models.CharField(max_length=100)),
                ('training_establishment', models.CharField(max_length=255)),
                ('training_address', models.TextField()),
                ('officer_in_charge', models.CharField(max_length=255)),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('training_duration', models.CharField(max_length=50)),
                ('field_of_training', models.CharField(max_length=255)),
                ('nic_copy', models.FileField(upload_to='student_docs/nic/')),
                ('agreement_form', models.FileField(upload_to='student_docs/agreement/')),
                ('work_site_form', models.FileField(upload_to='student_docs/worksite/')),
                ('placement_letter', models.FileField(upload_to='student_docs/placement/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('checked_ok', models.BooleanField(default=False)),
                ('admin_reg_number', models.CharField(blank=True, max_length=50, null=True)),
                ('form_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.formlink')),
            ],
            options={
                'unique_together': {('nic', 'form_link')},
            },
        ),
    ]
