# Generated by Django 5.2.8 on 2026-01-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formlink_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlink',
            name='district',
            field=models.CharField(default='Colombo', max_length=100),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='district',
            field=models.CharField(default='Colombo', max_length=100),
        ),
    ]
