# Generated by Django 5.2.8 on 2026-01-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_formlink_assigned_coordinator_novationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novationrequest',
            name='requested_subject',
        ),
        migrations.RemoveField(
            model_name='novationrequest',
            name='requested_university',
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='requested_work_site',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
