# Generated by Django 5.2.8 on 2026-02-02 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_novationrequest_requested_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='form_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.formlink'),
        ),
    ]
