# Generated by Django 5.2.8 on 2026-02-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_studentsubmission_marked_status_auditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlink',
            name='google_form_url',
            field=models.URLField(blank=True, help_text='Optional external Google Form URL', null=True),
        ),
    ]
