# Generated by Django 6.0.1 on 2026-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_coordinatorpendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorinvite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
