# Generated by Django 5.2.8 on 2026-03-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coordinatorinvite_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorinvite',
            name='email',
        ),
    ]
