# Generated by Django 5.2.8 on 2026-03-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_coordinatorinvite_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorinvite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
