# Generated by Django 5.2.8 on 2026-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_coordinatorinvite_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='column_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='head_office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='head_office_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='head_office_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='head_office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='head_office_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='officer_in_charge_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
