# Generated by Django 5.2.8 on 2026-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_studentsubmission_column_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='agreement_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='finalized_agreement_form',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/finalized_agreement/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='is_agreement_sent',
            field=models.BooleanField(default=False),
        ),
    ]
