# Generated by Django 6.0.1 on 2026-03-10 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_studentsubmission_agreement_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INSPECTOR', 'Inspector'), ('ASSESSOR', 'Assessor'), ('UNIVERSITY_COORDINATOR', 'University Coordinator')], max_length=50),
        ),
        migrations.CreateModel(
            name='StaffInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_type', models.CharField(choices=[('ASSESSOR', 'Assessor'), ('INSPECTOR', 'Inspector')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('USED', 'Used')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_staff_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_type', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('initials_name', models.CharField(blank=True, default='', max_length=255)),
                ('permanent_address', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('assessment_fields', models.JSONField(blank=True, null=True)),
                ('is_also_assessor', models.BooleanField(default=False)),
                ('assessor_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_registration', to=settings.AUTH_USER_MODEL)),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_registration', to='api.staffinvite')),
            ],
        ),
    ]
