# Generated by Django 5.2.8 on 2026-03-17 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_staffinvite_staffpendingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VivaPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(blank=True, limit_choices_to={'role': 'ASSESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_viva_panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VivaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viva_assignment', to='api.studentsubmission')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.vivapanel')),
            ],
            options={
                'ordering': ['panel', 'slot_number', 'scheduled_time'],
            },
        ),
    ]
