# Generated by Django 5.2.8 on 2026-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_vivapanel_vivaassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivapanel',
            name='batch_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vivapanel',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vivapanel',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
