# Generated by Django 5.2.8 on 2026-03-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_vivapanel_batch_year_vivapanel_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vivapanel',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='vivapanel',
            name='date',
        ),
        migrations.AddField(
            model_name='vivapanel',
            name='dates',
            field=models.JSONField(default=list),
        ),
    ]
