# Generated by Django 5.2.8 on 2026-03-19 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_vivapanel_options_remove_vivapanel_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_diary_mark', models.DecimalField(decimal_places=2, help_text='Daily Diary Mark', max_digits=5)),
                ('attendance_mark', models.DecimalField(decimal_places=2, help_text='Attendance Mark', max_digits=5)),
                ('technical_knowledge_mark', models.DecimalField(decimal_places=2, help_text='Technical Knowledge Mark', max_digits=5)),
                ('final_report_mark', models.DecimalField(decimal_places=2, help_text='Final Report Mark', max_digits=5)),
                ('total_mark', models.DecimalField(decimal_places=2, help_text='Calculated Total Mark', max_digits=5)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=20)),
                ('assessor_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_marks', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.vivaassignment')),
            ],
        ),
    ]
