# Generated by Django 5.2.8 on 2026-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_assessmentmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmark',
            name='attendance_mark',
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='daily_diary_mark',
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='final_report_mark',
        ),
        migrations.RemoveField(
            model_name='assessmentmark',
            name='technical_knowledge_mark',
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='evaluation_condition',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('INCOMPLETE_DIARY', 'Incomplete Daily Diary'), ('EXTEND', 'Extend'), ('VIVA_REPEAT', 'Viva Repeat')], default='NORMAL', max_length=50),
        ),
        migrations.AddField(
            model_name='assessmentmark',
            name='marks_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vivapanel',
            name='marking_criteria',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='assessmentmark',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('SPECIAL_STATUS', 'Special Status')], max_length=20),
        ),
    ]
