# Generated by Django 5.2.8 on 2026-03-26 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_assessmentmark_attendance_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student_count', models.IntegerField(default=0)),
                ('accomplishment_report', models.FileField(blank=True, null=True, upload_to='assessor_reports/accomplishment/')),
                ('claim_form', models.FileField(blank=True, null=True, upload_to='assessor_reports/claims/')),
                ('is_received_by_admin', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(limit_choices_to={'role': 'ASSESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('assessor', 'date')},
            },
        ),
    ]
