# Generated by Django 5.2.8 on 2026-05-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_assessment_fields_user_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novationrequest',
            name='admin_novation_form',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/novation_forms/'),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='is_read_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_divisional_secretariat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_field_of_training',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_officer_in_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_officer_in_charge_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_training_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_training_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_training_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novationrequest',
            name='new_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='has_second_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='received_approval_for_resubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_divisional_secretariat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_field_of_training',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_officer_in_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_officer_in_charge_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_placement_form',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/second_placement/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_training_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_training_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_training_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_training_establishment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
