# Generated by Django 5.2.8 on 2026-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_novationrequest_admin_novation_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlink',
            name='number_of_trainings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_agreement_form',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/second_agreement/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_placement_letter',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/second_placement_letter/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='second_work_site_form',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/second_worksite/'),
        ),
    ]
