# Generated by Django 5.2.8 on 2026-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_formlink_number_of_trainings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='second_agreement_form',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='second_placement_letter',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='second_work_site_form',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='has_phase2_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_agreement_form',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/phase2_agreement/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_divisional_secretariat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_field_of_training',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_officer_in_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_officer_in_charge_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_placement_letter',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/phase2_placement_letter/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_training_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_training_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_training_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_training_establishment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_work_site_form',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/phase2_worksite/'),
        ),
    ]
