# Generated by Django 5.2.8 on 2026-05-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_studentsubmission_second_agreement_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novationrequest',
            name='training_phase',
            field=models.CharField(choices=[('PHASE_1', 'Phase 1'), ('PHASE_2', 'Phase 2')], default='PHASE_1', max_length=20),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='has_phase2_second_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_divisional_secretariat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_field_of_training',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_officer_in_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_officer_in_charge_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_placement_form',
            field=models.FileField(blank=True, null=True, upload_to='student_docs/phase2_second_placement/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_training_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_training_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_training_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_training_establishment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='phase2_second_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
