# Generated by Django 5.2.8 on 2026-05-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_novationrequest_training_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivapanel',
            name='training_phase',
            field=models.CharField(choices=[('PHASE_1', 'Phase 1'), ('PHASE_2', 'Phase 2')], default='PHASE_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='vivaassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_assignments', to='api.studentsubmission'),
        ),
    ]
